/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by PluginManager.generateManagedPluginsFile().
import type { PluginScript, ScriptMatchRule } from "@playwrong/plugin-sdk";
import * as pluginModule0 from "../../../../plugins/installed/example.github.repo-manager/src/index";

type PluginModuleLike = { pluginScripts?: PluginScript[]; default?: PluginScript[] };

function normalizePluginScripts(input: unknown): PluginScript[] {
  const candidate = input as PluginModuleLike;
  if (Array.isArray(candidate.pluginScripts)) {
    return candidate.pluginScripts;
  }
  if (Array.isArray(candidate.default)) {
    return candidate.default;
  }
  return [];
}

function mergeScope(pluginId: string, scripts: PluginScript[], scope: ScriptMatchRule): PluginScript[] {
  return scripts.map((script, index) => {
    const scriptId = script.scriptId || `${pluginId}.${index + 1}`;
    const rules = script.rules && script.rules.length > 0 ? [scope, ...script.rules] : [scope];
    return { ...script, scriptId, rules };
  });
}

const managedPluginEntries: Array<{ pluginId: string; scripts: PluginScript[]; scope: ScriptMatchRule }> = [
  {
    pluginId: "example.github.repo-manager",
    scripts: normalizePluginScripts(pluginModule0),
    scope: {
        "hosts": [
          "github.com",
          "www.github.com"
        ]
      }
  }
];

export const managedPluginScripts: PluginScript[] = managedPluginEntries.flatMap((entry) =>
  mergeScope(entry.pluginId, entry.scripts, entry.scope)
);

export const managedPluginInfo = managedPluginEntries.map((entry) => ({
  pluginId: entry.pluginId,
  scriptCount: entry.scripts.length
}));
